export const GET_PRODUCTS_RANDOM = 'GET_PRODUCTS_RANDOM';
export const NEWS_PRODUCTS = 'NEWS_PRODUCTS';
export const ALL_PRODUCTS = 'ALL_PRODUCTS';
export const GET_DETAILS = 'GET_DETAILS';
export const RESET_DETAILS = 'RESET_DETAILS';
export const GET_STOCK_DETAILS = 'GET_STOCK_DETAILS';
export const RESET_STOCK_DETAILS = 'RESET_STOCK_DETAILS';